### ISSUE TITLE
Same print behaviour for run/start/startFromArgs

### ISSUE THREAD

**Issue by passsy** [bsutton/dcli#134]
I switched from `startFromArgs` to `start` and noticed that `stdout/stderr` aren't printed. This was very unexpected.

### Current behavior

- `startFromArgs` uses `Progress.print()`
- `run` uses `Progress(print, stderr: printerr)` which is equivalent to `Progress.print()`
- `start` uses **`Progress.devNull()`** which is the fallback of `RunnableProcess.run`

Please make sure that all 3 methods use `Progress.print()` as default.

**Comment by bsutton** [comment]
The difference between start and run was intentional.

The concept of run was 'here is this quick way to run a command without thinking about it and I don't need to process the output.

The start command is designed to provide detailed control over running a command and processing the output.

The key difference between being that start was about processing data whilst run wasn't.

The difference between start and startWithArgs was not intended and I agree that its should be modified to be identical to start.

I guess I would like to see broader community dissatisfaction with the differences between run and start before I modify the default behaviour of start.

**Comment by bsutton** [comment]
The latest version of dcli makes start and startWithArgs consistent.

The run command hasn't been changed as it works as intended.
